# Generated by Django 4.2.2 on 2023-07-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=200)),
                ('gameDescription', models.CharField(max_length=200)),
                ('gameBin', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
