# Generated by Django 4.2.2 on 2023-07-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gameBin',
            new_name='gbin',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gameName',
            new_name='name',
        ),
    ]
