# Generated by Django 4.2.2 on 2023-07-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gbin',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
